// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_START  RequestType = 0
	RequestType_STOP   RequestType = 1
	RequestType_CANCEL RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "CANCEL",
	}
	RequestType_value = map[string]int32{
		"START":  0,
		"STOP":   1,
		"CANCEL": 2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

type RequestCase int32

const (
	RequestCase_D2D6 RequestCase = 0
	RequestCase_FLIP RequestCase = 1
	RequestCase_MINT RequestCase = 2
)

// Enum value maps for RequestCase.
var (
	RequestCase_name = map[int32]string{
		0: "D2D6",
		1: "FLIP",
		2: "MINT",
	}
	RequestCase_value = map[string]int32{
		"D2D6": 0,
		"FLIP": 1,
		"MINT": 2,
	}
)

func (x RequestCase) Enum() *RequestCase {
	p := new(RequestCase)
	*p = x
	return p
}

func (x RequestCase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCase) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[1].Descriptor()
}

func (RequestCase) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[1]
}

func (x RequestCase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestCase.Descriptor instead.
func (RequestCase) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

type RnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.RequestType" json:"type,omitempty"`
	Case      RequestCase `protobuf:"varint,2,opt,name=case,proto3,enum=pb.RequestCase" json:"case,omitempty"`
	StopLimit int64       `protobuf:"varint,3,opt,name=stopLimit,proto3" json:"stopLimit,omitempty"`
}

func (x *RnRequest) Reset() {
	*x = RnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RnRequest) ProtoMessage() {}

func (x *RnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RnRequest.ProtoReflect.Descriptor instead.
func (*RnRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *RnRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_START
}

func (x *RnRequest) GetCase() RequestCase {
	if x != nil {
		return x.Case
	}
	return RequestCase_D2D6
}

func (x *RnRequest) GetStopLimit() int64 {
	if x != nil {
		return x.StopLimit
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash      string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Demo2D6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number1 int64      `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2 int64      `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
	Details *RnDetails `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *Demo2D6) Reset() {
	*x = Demo2D6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Demo2D6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo2D6) ProtoMessage() {}

func (x *Demo2D6) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo2D6.ProtoReflect.Descriptor instead.
func (*Demo2D6) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *Demo2D6) GetNumber1() int64 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *Demo2D6) GetNumber2() int64 {
	if x != nil {
		return x.Number2
	}
	return 0
}

func (x *Demo2D6) GetDetails() *RnDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type DemoFlip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head    bool       `protobuf:"varint,1,opt,name=head,proto3" json:"head,omitempty"`
	Details *RnDetails `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *DemoFlip) Reset() {
	*x = DemoFlip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoFlip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoFlip) ProtoMessage() {}

func (x *DemoFlip) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoFlip.ProtoReflect.Descriptor instead.
func (*DemoFlip) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *DemoFlip) GetHead() bool {
	if x != nil {
		return x.Head
	}
	return false
}

func (x *DemoFlip) GetDetails() *RnDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type RnDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           RequestCase    `protobuf:"varint,2,opt,name=type,proto3,enum=pb.RequestCase" json:"type,omitempty"`
	StartTimestamp int64          `protobuf:"varint,5,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	StopTimestamp  int64          `protobuf:"varint,6,opt,name=stopTimestamp,proto3" json:"stopTimestamp,omitempty"`
	ElapsedTime    int64          `protobuf:"varint,7,opt,name=elapsedTime,proto3" json:"elapsedTime,omitempty"`
	TxSize         int64          `protobuf:"varint,8,opt,name=txSize,proto3" json:"txSize,omitempty"`
	Txs            []*Transaction `protobuf:"bytes,9,rep,name=txs,proto3" json:"txs,omitempty"`
	TxsHash        string         `protobuf:"bytes,10,opt,name=txsHash,proto3" json:"txsHash,omitempty"`
	Seed           int64          `protobuf:"varint,11,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *RnDetails) Reset() {
	*x = RnDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RnDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RnDetails) ProtoMessage() {}

func (x *RnDetails) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RnDetails.ProtoReflect.Descriptor instead.
func (*RnDetails) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *RnDetails) GetType() RequestCase {
	if x != nil {
		return x.Type
	}
	return RequestCase_D2D6
}

func (x *RnDetails) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *RnDetails) GetStopTimestamp() int64 {
	if x != nil {
		return x.StopTimestamp
	}
	return 0
}

func (x *RnDetails) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *RnDetails) GetTxSize() int64 {
	if x != nil {
		return x.TxSize
	}
	return 0
}

func (x *RnDetails) GetTxs() []*Transaction {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *RnDetails) GetTxsHash() string {
	if x != nil {
		return x.TxsHash
	}
	return ""
}

func (x *RnDetails) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type TxSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int64 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *TxSize) Reset() {
	*x = TxSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSize) ProtoMessage() {}

func (x *TxSize) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSize.ProtoReflect.Descriptor instead.
func (*TxSize) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *TxSize) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqAck RequestType `protobuf:"varint,1,opt,name=reqAck,proto3,enum=pb.RequestType" json:"reqAck,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetReqAck() RequestType {
	if x != nil {
		return x.ReqAck
	}
	return RequestType_START
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*Packet_RnDetails
	//	*Packet_Demo2D6
	//	*Packet_DemoFlip
	//	*Packet_Ack
	//	*Packet_Size
	Response isPacket_Response `protobuf_oneof:"response"`
	// Types that are assignable to Request:
	//	*Packet_StartNstop
	Request isPacket_Request `protobuf_oneof:"request"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (m *Packet) GetResponse() isPacket_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *Packet) GetRnDetails() *RnDetails {
	if x, ok := x.GetResponse().(*Packet_RnDetails); ok {
		return x.RnDetails
	}
	return nil
}

func (x *Packet) GetDemo2D6() *Demo2D6 {
	if x, ok := x.GetResponse().(*Packet_Demo2D6); ok {
		return x.Demo2D6
	}
	return nil
}

func (x *Packet) GetDemoFlip() *DemoFlip {
	if x, ok := x.GetResponse().(*Packet_DemoFlip); ok {
		return x.DemoFlip
	}
	return nil
}

func (x *Packet) GetAck() *Ack {
	if x, ok := x.GetResponse().(*Packet_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *Packet) GetSize() *TxSize {
	if x, ok := x.GetResponse().(*Packet_Size); ok {
		return x.Size
	}
	return nil
}

func (m *Packet) GetRequest() isPacket_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *Packet) GetStartNstop() *RnRequest {
	if x, ok := x.GetRequest().(*Packet_StartNstop); ok {
		return x.StartNstop
	}
	return nil
}

type isPacket_Response interface {
	isPacket_Response()
}

type Packet_RnDetails struct {
	RnDetails *RnDetails `protobuf:"bytes,1,opt,name=rnDetails,proto3,oneof"`
}

type Packet_Demo2D6 struct {
	Demo2D6 *Demo2D6 `protobuf:"bytes,2,opt,name=demo2d6,proto3,oneof"`
}

type Packet_DemoFlip struct {
	DemoFlip *DemoFlip `protobuf:"bytes,6,opt,name=demoFlip,proto3,oneof"`
}

type Packet_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type Packet_Size struct {
	Size *TxSize `protobuf:"bytes,5,opt,name=size,proto3,oneof"`
}

func (*Packet_RnDetails) isPacket_Response() {}

func (*Packet_Demo2D6) isPacket_Response() {}

func (*Packet_DemoFlip) isPacket_Response() {}

func (*Packet_Ack) isPacket_Response() {}

func (*Packet_Size) isPacket_Response() {}

type isPacket_Request interface {
	isPacket_Request()
}

type Packet_StartNstop struct {
	StartNstop *RnRequest `protobuf:"bytes,4,opt,name=startNstop,proto3,oneof"`
}

func (*Packet_StartNstop) isPacket_Request() {}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x73, 0x0a, 0x09, 0x52, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x61,
	0x73, 0x65, 0x52, 0x04, 0x63, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x6f,
	0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3f, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x66, 0x0a, 0x07, 0x44, 0x65, 0x6d, 0x6f, 0x32,
	0x44, 0x36, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x12, 0x27, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0x47, 0x0a, 0x08, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6c, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12,
	0x27, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x89, 0x02, 0x0a, 0x09, 0x52, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x70,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6c, 0x61,
	0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x78, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x78, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x73, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x73, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x54, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x2e, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x27, 0x0a,
	0x06, 0x72, 0x65, 0x71, 0x41, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x72, 0x65, 0x71, 0x41, 0x63, 0x6b, 0x22, 0x93, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x09, 0x72, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x27, 0x0a, 0x07, 0x64, 0x65, 0x6d, 0x6f, 0x32, 0x64, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x32, 0x44, 0x36, 0x48, 0x00,
	0x52, 0x07, 0x64, 0x65, 0x6d, 0x6f, 0x32, 0x64, 0x36, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x65, 0x6d,
	0x6f, 0x46, 0x6c, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6c, 0x69, 0x70, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x6d,
	0x6f, 0x46, 0x6c, 0x69, 0x70, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x73, 0x74,
	0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x01, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4e, 0x73, 0x74, 0x6f, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2a, 0x2e, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x02, 0x2a, 0x2b, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x32, 0x44, 0x36, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4c, 0x49, 0x50, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_model_proto_goTypes = []interface{}{
	(RequestType)(0),    // 0: pb.RequestType
	(RequestCase)(0),    // 1: pb.RequestCase
	(*RnRequest)(nil),   // 2: pb.RnRequest
	(*Transaction)(nil), // 3: pb.Transaction
	(*Demo2D6)(nil),     // 4: pb.Demo2D6
	(*DemoFlip)(nil),    // 5: pb.DemoFlip
	(*RnDetails)(nil),   // 6: pb.RnDetails
	(*TxSize)(nil),      // 7: pb.TxSize
	(*Ack)(nil),         // 8: pb.Ack
	(*Packet)(nil),      // 9: pb.Packet
}
var file_model_proto_depIdxs = []int32{
	0,  // 0: pb.RnRequest.type:type_name -> pb.RequestType
	1,  // 1: pb.RnRequest.case:type_name -> pb.RequestCase
	6,  // 2: pb.Demo2D6.details:type_name -> pb.RnDetails
	6,  // 3: pb.DemoFlip.details:type_name -> pb.RnDetails
	1,  // 4: pb.RnDetails.type:type_name -> pb.RequestCase
	3,  // 5: pb.RnDetails.txs:type_name -> pb.Transaction
	0,  // 6: pb.Ack.reqAck:type_name -> pb.RequestType
	6,  // 7: pb.Packet.rnDetails:type_name -> pb.RnDetails
	4,  // 8: pb.Packet.demo2d6:type_name -> pb.Demo2D6
	5,  // 9: pb.Packet.demoFlip:type_name -> pb.DemoFlip
	8,  // 10: pb.Packet.ack:type_name -> pb.Ack
	7,  // 11: pb.Packet.size:type_name -> pb.TxSize
	2,  // 12: pb.Packet.startNstop:type_name -> pb.RnRequest
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Demo2D6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoFlip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RnDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Packet_RnDetails)(nil),
		(*Packet_Demo2D6)(nil),
		(*Packet_DemoFlip)(nil),
		(*Packet_Ack)(nil),
		(*Packet_Size)(nil),
		(*Packet_StartNstop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
